import '@/sass/main-styles.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'gYmantic | Bring fitness to your world',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
