'use client';
//import type { Metadata } from 'next';
import useDarkMode from '@/hooks/useDarkMode';
import '../scss/main-styles.scss';

/*export const metadata: Metadata = {
  title: 'gYmantic | Bring fitness to your world',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'shortcut icon',
      type: 'image/svg+xml',
      url: '/icon.svg'
    }
  ]
};*/

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode] = useDarkMode();
  return (
    <html lang='en'>
      <body data-theme={darkMode ? 'darkMode' : 'light'}>{children}</body>
    </html>
  );
}
